In [1]:
import numpy as np
import pandas as pd

#initialize sequence
seq1 = 'MHHNALQRRTVWVNAY'
seq2 = 'MHHALQRRTVWVNAY'

mat = np.zeros((len(seq1)+1, len(seq2)+1))

pd.DataFrame(mat)

     0    1    2    3    4    5    6   ...   9    10   11   12   13   14   15
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
16  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[17 rows x 16 columns]

In [2]:
#make dotplot matrix 
d_mat = np.zeros((len(seq1), len(seq2)))
for i in range(len(seq1)):
    for j in range(len(seq2)):
        if seq1[i] == seq2[j]:
            d_mat[i][j] = 1
        else:     
            d_mat[i][j] = 0

d_mat
pd.DataFrame(d_mat)

     0    1    2    3    4    5    6    7    8    9    10   11   12   13   14
0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1   0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2   0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
4   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
5   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7   0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
14  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [10]:
match_score = 1
nomatch_score = 0
gap_penalty = -2

In [11]:
def NW(mat):
   for i in range(len(seq1)+1):
       mat[i][0] = i*gap_penalty
   for j in range(len(seq2)+1):
       mat[0][j] = j*gap_penalty
#comparing values
   for i in range(1,len(seq1)+1):
       for j in range(1,len(seq2)+1):
                mat[i][j] = max(mat[i-1][j-1]+d_mat[i-1][j-1], mat[i-1][j]+gap_penalty, mat[i][j-1]+gap_penalty)

   return(mat)

NW(mat)
pd.DataFrame(mat)

      0     1     2     3     4     5   ...    10    11    12    13    14    15
0    0.0  -2.0  -4.0  -6.0  -8.0 -10.0  ... -20.0 -22.0 -24.0 -26.0 -28.0 -30.0
1   -2.0   1.0  -1.0  -3.0  -5.0  -7.0  ... -17.0 -19.0 -21.0 -23.0 -25.0 -27.0
2   -4.0  -1.0   2.0   0.0  -2.0  -4.0  ... -14.0 -16.0 -18.0 -20.0 -22.0 -24.0
3   -6.0  -3.0   0.0   3.0   1.0  -1.0  ... -11.0 -13.0 -15.0 -17.0 -19.0 -21.0
4   -8.0  -5.0  -2.0   1.0   3.0   1.0  ...  -9.0 -11.0 -13.0 -14.0 -16.0 -18.0
5  -10.0  -7.0  -4.0  -1.0   2.0   3.0  ...  -7.0  -9.0 -11.0 -13.0 -13.0 -15.0
6  -12.0  -9.0  -6.0  -3.0   0.0   3.0  ...  -5.0  -7.0  -9.0 -11.0 -13.0 -13.0
7  -14.0 -11.0  -8.0  -5.0  -2.0   1.0  ...  -3.0  -5.0  -7.0  -9.0 -11.0 -13.0
8  -16.0 -13.0 -10.0  -7.0  -4.0  -1.0  ...   0.0  -2.0  -4.0  -6.0  -8.0 -10.0
9  -18.0 -15.0 -12.0  -9.0  -6.0  -3.0  ...   2.0   0.0  -2.0  -4.0  -6.0  -8.0
10 -20.0 -17.0 -14.0 -11.0  -8.0  -5.0  ...   5.0   3.0   1.0  -1.0  -3.0  -5.0
11 -22.0 -19.0 -16.0 -13.0 -10.0  -7.0  ...   8.0   6.0   4.0   2.0   0.0  -2.0
12 -24.0 -21.0 -18.0 -15.0 -12.0  -9.0  ...   6.0   9.0   7.0   5.0   3.0   1.0
13 -26.0 -23.0 -20.0 -17.0 -14.0 -11.0  ...   4.0   7.0  10.0   8.0   6.0   4.0
14 -28.0 -25.0 -22.0 -19.0 -16.0 -13.0  ...   2.0   5.0   8.0  11.0   9.0   7.0
15 -30.0 -27.0 -24.0 -21.0 -18.0 -15.0  ...   0.0   3.0   6.0   9.0  12.0  10.0
16 -32.0 -29.0 -26.0 -23.0 -20.0 -17.0  ...  -2.0   1.0   4.0   7.0  10.0  13.0

[17 rows x 16 columns]

In [20]:
ResultA = ""
ResultB = ""
i = len(seq1)
j = len(seq2)
while (i>0 or j>0):

  if (i>0 and j>0 and mat[i][j] == mat[i-1][j-1] + d_mat[i-1][j-1]):
    ResultA = seq1[i-1] + ResultA
    ResultB = seq2[j-1] + ResultB
    i = i - 1
    j = j - 1

  elif (i>0 and mat[i][j] == mat[i-1][j] + gap_penalty):
    ResultA = seq1[i-1] + ResultA
    ResultB = "-" + ResultB
    i = i - 1
  
  else:
    ResultA = "-" + ResultA
    ResultB = seq2[j-1] + ResultB
    j = j - 1

In [21]:
print(ResultA)
print(ResultB)

MHHNALQRRTVWVNAY
MHH-ALQRRTVWVNAY

In [29]:
from Bio.SubsMat.MatrixInfo import blosum62 as blosum

blosum.update(((b,a),val) for (a,b),val in list(blosum.items()))

def score_pairwise(seq1, seq2, matrix, gap_s, gap_e, gap = True):
    for A,B in zip(seq1, seq2):
        diag = ('-'==A) or ('-'==B)
        yield (gap_e if gap else gap_s) if diag else matrix[(A,B)]
        gap = diag

seq1 = ResultA
seq2 = ResultB

print(sum(score_pairwise(seq1, seq2, blosum, -6, -1)))

79